# Generated by Django 4.0.6 on 2022-12-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='cover',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
