# Generated by Django 4.0.2 on 2022-03-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melanomas', '0004_articles_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='image',
            new_name='images',
        ),
    ]
