# Generated by Django 4.0.2 on 2022-03-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomas', '0005_rename_image_articles_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='images',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
    ]
