# Generated by Django 4.0.2 on 2022-03-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomas', '0006_alter_articles_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddField(
            model_name='articles',
            name='book',
            field=models.FileField(default='SOME STRING', upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='images',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение'),
        ),
    ]
