# Generated by Django 4.0.2 on 2022-03-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomas', '0007_delete_book_alter_articles_options_articles_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('cover', models.ImageField(upload_to='images/')),
                ('book', models.FileField(upload_to='books/')),
            ],
        ),
        migrations.RemoveField(
            model_name='articles',
            name='book',
        ),
        migrations.AlterField(
            model_name='articles',
            name='images',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
    ]
