# Generated by Django 4.1.3 on 2022-12-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melanomas', '0008_book_remove_articles_book_alter_articles_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='images',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
    ]
